// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Piranha.Data.EF.SQLite;

#nullable disable

namespace Piranha.Data.EF.SQLite.Migrations
{
    [DbContext(typeof(SQLiteDb))]
    [Migration("20250522000000_AddWorkflowStageRoles")]
    partial class AddWorkflowStageRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");
            
            // Note: This is a simplified designer file. 
            // The full model would be auto-generated by EF tools.
            // For now, we'll rely on the main migration file.
#pragma warning restore 612, 618
        }
    }
}
